const CONFIG = {
    MAX_VIDA: 100,
    MAX_STAMINA: 100,
    STAMINA_RECUPERADA: 25,
    DANO_ATACAR: 15,
    DANO_ESPECIAL_BLOQUEADO: 20,
    DANO_ESPECIAL_NAO_BLOQUEADO: 35,
    CUSTO_ATACAR: 15,
    CUSTO_ESPECIAL: 100,
    CUSTO_BLOQUEAR: 10,
    RECARREGAR_COMANDO: 'R',
    BLOQUEAR_COMANDO: 'B',
    ATACAR_COMANDO: 'A',
    ESPECIAL_COMANDO: 'E',
    TOTAL_COMANDOS_LOTE: 10
};

module.exports = CONFIG;