const estados = {
    PARADO: 'PARADO',
    BLOQUEANDO: 'BLOQUEANDO',
    ATACANDO: 'ATACANDO',
    ATAQUE_ESPECIAL: 'ATAQUE ESPECIAL',
    ATINGIDO: 'ATINGIDO',
    SEM_STAMINA: 'SEM STAMINA',
    RECARREGANDO_STAMINA: 'RECARREGANDO STAMINA',
    VENCEU: 'VENCEU',
    DERROTADO: 'DERROTADO',
    EMPATADO: 'EMPATADO'
};

module.exports = estados;